### ISSUE TITLE
Better grouping for SQL Server error messages

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/Rollbar.NET#17]
Details in https://app.clubhouse.io/rollbar/story/1723/better-grouping-for-sql-server-error-messages-via-c

**Comment by rokob** [comment]
C# passes on SQL Server exception messages which have interpolated data. This leads to what is basically the same exception getting fingerprinted differently because the message will be different. See the error messages here: https://technet.microsoft.com/en-us/library/cc645603%28v=sql.105%29.aspx

It would be nice to work out how to fingerprint based on the the part of the exception that is fixed and doesn't change with input. We do something like this in Python. I think this is a nice to have, and is something that we should make easy to do, but not necessary for the v1 alpha release.

I am going to add to a new milestone for v1 which means not needed for the alpha.

**Comment by coryvirok** [comment]
Closing this since we will address it on the backend.
