### ISSUE TITLE
Unable to use Rollbar with Xamarin.Forms for Android project since version 1.5.1

### ISSUE THREAD

**Issue by lanarchyste** [rollbar/Rollbar.NET#173]
the ConnectionLeaseTimeout property used in the RollbarClient constructor is not implemented in Mono.

`[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.TypeInitializationException: The type initializer for 'NestedSingleInstance' threw an exception. ---> System.NotImplementedException: The method or operation is not implemented.
[MonoDroid]   at System.Net.ServicePoint.set_ConnectionLeaseTimeout (System.Int32 value) [0x00005] in <5a97d41d36694fb19855c17429527b10>:0 
[MonoDroid]   at Rollbar.RollbarClient..ctor (Rollbar.RollbarConfig config, System.Net.Http.HttpClient httpClient) [0x0009a] in <ec422a283da843fd8537e1b41d259a86>:0 
[MonoDroid]   at Rollbar.RollbarLogger..ctor (System.Boolean isSingleton) [0x0006d] in <ec422a283da843fd8537e1b41d259a86>:0 
[MonoDroid]   at Rollbar.RollbarFactory.CreateNew (System.Boolean isSingleton) [0x00000] in <ec422a283da843fd8537e1b41d259a86>:0 
[MonoDroid]   at Rollbar.RollbarLocator+NestedSingleInstance..cctor () [0x00000] in <ec422a283da843fd8537e1b41d259a86>:0 
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
[MonoDroid]   at Kibati.Droid.Services.ErrorTrackingDroid..ctor () [0x00021] in <6429c236608443f4af2892a66de5c96a>:0 
[MonoDroid]   at Kibati.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0003b] in <6429c236608443f4af2892a66de5c96a>:0 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <263adecfa58f4c449f1ff56156d886fd>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.b0b1f11c-3bf5-4cd6-a3d8-39ea0d9b97ed(intptr,intptr,intptr)`

**Comment by akornich** [comment]
@lanarchyste, what version of Xamarin.forms do you use?

**Comment by lanarchyste** [comment]
I am using Xamarin.Forms 3.1.0.637273

Here is the detail of my environment:

> Visual Studio Community 2017 for Mac
Version 7.5.3 (build 7)
Installation UUID: c92dca29-4e75-4725-9978-d4057660d9f4
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
	Package version: 510010057

> Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /usr/local/Caskroom/android-platform-tools/28.0.0
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

> SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

> Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by akornich** [comment]
@lanarchyste , thank you. intersting, Mono since 5.4 claims to be compliant with .NET Standard 2.0 [https://docs.microsoft.com/en-us/dotnet/standard/net-standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
but still looks like it does not implement ConnectionLeaseTimeout property.
I thinks we can try guarding the property assignment in try-catch block and just swallowing the exception when it it happens under Mono. But this would leave you with default value of "-1" that means "no timeout" or maintaining the service point indefinitely. That means any possible changes of DNS records will go unnoticed. This is probably very unlikely case for most of applications but still could be a problem potentially. On the other hand once Mono actually implements the property everything will run by the original plan.

**Comment by lanarchyste** [comment]
Instead of a try / catch that is expensive for the CLR, would not it be better to detect the runtime ?

With the following code for example:
`return Type.GetType ("Mono.Runtime") != null;`

Or even better, with a method that would perform the problem code but which would not be called if we are on mono using the conditional attribute.

**Comment by akornich** [comment]
@lanarchyste , in general, you are right. but for this specific case, i believe, the try/catch is most optimal solution. here is why: the timeout is only set when a RollbarLogger instance is configured, so that if it is used as a singleton (probably, the most common scenario) it happens once per hosting application life-time. Once Mono actually implements this property - no exception any more and the complete intended functionality is already there. Also, this approach would not interfere with our current use of conditional compilation based on specific .NET Standard target implementation. We do use it in cases when we do know that specific targeted framework does not even define an API. In this case, judging by the exception type and the expected support of this >NET Standard API in Mono, the property setter is defined but has the "default" NotImplemented "implementation" until they actually fill in the blanks.

**Comment by akornich** [comment]
@lanarchyste , thanks for the approval. i'll try to publish this fix sometime during upcoming Monday. stay tuned. thanks for the provided info!
