### ISSUE TITLE
SDK not sending the crash log of Xamarin Android/ios app .

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/Rollbar.NET#187]
Hi, 

I have integrated Rollbar Xamarin SDK in my application but it's not sending any crash log to the Rollbar dashboard. Below are few more observations that i have observed.
I have crashed the app with following code but did not get any crash log on the Rollbar dashboard.
```
namespace App2
{
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
                        throw new Exception("Throw unhandled exception");
		}
	}
}
```

However, It's working fine with handled exception if i am using it with try and catch block. Getting correct error trackback on Rollbar console.

```
   try
     {
        if (value.Length == 0) // <-- Causes exception
        {
            Console.WriteLine(value); // <-- Never reached
        }
    }catch(Exception e)
    {
		RollbarLocator.RollbarInstance.Error(e);
    }

```
![xamarin error](https://user-images.githubusercontent.com/32199575/46167205-cd5a1400-c2b2-11e8-9f52-625e88a9246c.PNG)

Could you please look into it. Below is my sample app repo you can see if you want to more investigate.
https://github.com/RollbarExample/Rollbar-Xamarin-Example

Thanks.

**Comment by akornich** [comment]
@RollbarExample , as for now, Rollbar.NET implements only common cross-platform functionality (across .NET Framework, or .NET Core, or Xamarin based application hosts that could run on variety OSs: Windows, Linux, macOS, iOS, Android) - i.e. it the hosting application responsibility to explicitly  invoke any of the Rollbar.ILogger interface methods on a rollbar instance to send any payload to Rollbar API.

As far as I know, the crash log is applicable to only Apple platform (I can not speak for Android since I have no experience there). I would expect that the hosting app that runs on any Apple platform would need to check existence of a new crash log on its startup and, if needed, forward it to Rollbar API via one of the Rollbar.NET logger instances. Remember, any Rollbar notifier SDK is just a delivery mechanism to send data from a hosting app to the Rollbar API. 

Rollbar.NET notifier specifically can run on so many platforms and application architecture types that it should not be expected to know all the specifics of every platform or application architecture to just magically integrate itself. We are making effort add some platform and/or application architecture specific plug-ins to the SDK. These plug-ins would simplify Rollbar.NET integration effort for a specific platform/architecture/application-framework/common-logging-framework. For example, we already have RollbarMiddleware plugin for ASP.Net Core application architecture or RollbarTraceListener plugin (will available starting next official release of the SDK) that naturally fits into any application that already actively uses common .NET tracing infrastructure (available in both .NET Framework and .NET Core, and is a part of .NET Standard).

@rivkahstandig3636  and @jessewgibbs, as an alternative, we can probably implement a new conditional feature of Rollbar.NET to look for crash log when it runs on Apple platforms and forward it to Rollbar API (if there is any crash log) - similar to how Rollbar-iOS does it.

@RollbarExample , may I ask what is your reasoning for linking this issue to #153 that has nothing to do with handling crash logs?

**Comment by akornich** [comment]
@RollbarExample , i just cloned the repo with your sample app. its Android project does not compile due to missing resources:
Severity	Code	Description	Project	File	Line	Suppression State
Error		No resource found that matches the given name: attr 'windowActionBar'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2	
Error		No resource found that matches the given name: attr 'colorPrimaryDark'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2	
Error		Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2	
Error		No resource found that matches the given name: attr 'windowNoTitle'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2	
Error		No resource found that matches the given name: attr 'colorPrimary'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2	
Error		No resource found that matches the given name: attr 'colorAccent'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	3	
Error		Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	4	
Error		No resource found that matches the given name: attr 'colorAccent'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	4	
Error		No resource found that matches the given name: attr 'windowActionModeOverlay'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	4

**Comment by akornich** [comment]
@RollbarExample , btw, here is some interesting info I just came across.
It looks like that to properly catch unhandled exception in a Xamarin app there are multiple place to tap in. So far, you tapped into App5/App.xaml.cs's App() constructor (currentDomain's UnahandledException event). However, it appears that you need to do similar handlers in all the platform specific projects:

Android:

// In OnCreate,

AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
TaskScheduler.UnobservedTaskException += TaskSchedulerOnUnobservedTaskException;
AndroidEnvironment.UnhandledExceptionRaiser += AndroidEnvironmentOnUnhandledException;
iOS:

// In FinishedLaunching:

AppDomain.CurrentDomain.UnhandledException += async (sender, e) =>
TaskScheduler.UnobservedTaskException += async (sender, e) =>
UWP:

// In OnLaunched:

UnhandledException += OnUnhandledException;

where you would have to invoke the rollbar instance to send captured exceptions in all of these additional event handlers.

Please, let me know if this step unblock you...

**Comment by RollbarExample** [comment]
@akornich 
@RollbarExample , may I ask what is your reasoning for linking this issue to #153 that has nothing to do with handling crash logs?

Yes this one is also belongs to the #153 but there we were talking about unhadled exception in UWP platform. However here we are talking about android/ios platform.

Crash log is nothing but unhandled/runtime exception which occurs during the running state of application.

**Comment by RollbarExample** [comment]
> @RollbarExample , btw, here is some interesting info I just came across.
> It looks like that to properly catch all unhandled exceptions in a Xamarin app there are multiple places to tap in. So far, you tapped into App5/App.xaml.cs's App() constructor (currentDomain's UnahandledException event). However, it appears that you need to do similar handlers in all the platform specific projects:
> 
> Android:
> // In OnCreate,
> 
> AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
> TaskScheduler.UnobservedTaskException += TaskSchedulerOnUnobservedTaskException;
> AndroidEnvironment.UnhandledExceptionRaiser += AndroidEnvironmentOnUnhandledException;
> 
> iOS:
> // In FinishedLaunching:
> 
> AppDomain.CurrentDomain.UnhandledException += async (sender, e) =>
> TaskScheduler.UnobservedTaskException += async (sender, e) =>
> 
> UWP:
> // In OnLaunched:
> 
> UnhandledException += OnUnhandledException;
> 
> where you would have to invoke the rollbar instance to send captured exceptions in all of these additional event handlers.
> 
> Please, let me know if this step unblock you.

So i have tried this with android platform by invoking ` RollbarLocator.RollbarInstance.AsBlockingLogger(TimeSpan.FromSeconds(10)).
                 Critical(e);` 
But it's not sending the unhandled exception(Crash log) to the Rollbar console. Here is the complete android main activity code.
```
using System;

using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;
using System.IO;
using System.Threading.Tasks;
using Rollbar;

namespace App2.Droid
{
    [Activity(Label = "App2", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;
            base.OnCreate(bundle);
            AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
            TaskScheduler.UnobservedTaskException += TaskSchedulerOnUnobservedTaskException;
            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());
        }

       private void ToLogUnhandledException(Exception exception)
        {
            //RollbarLocator.RollbarInstance.Info("Exception is not null");
            //Console.WriteLine(ex);
            RollbarLocator.RollbarInstance.AsBlockingLogger(TimeSpan.FromSeconds(10)).Critical(exception);
        }

        private void TaskSchedulerOnUnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs unobservedTaskExceptionEventArgs)
        {
            var newExc = new Exception("TaskSchedulerOnUnobservedTaskException", unobservedTaskExceptionEventArgs.Exception);
            ToLogUnhandledException(newExc);
        }

       private  void CurrentDomainOnUnhandledException(object sender, UnhandledExceptionEventArgs unhandledExceptionEventArgs)
        {
            var newExc = new Exception("CurrentDomainOnUnhandledException", unhandledExceptionEventArgs.ExceptionObject as Exception);
            ToLogUnhandledException(newExc);
        }
    }
}
```

**Comment by RollbarExample** [comment]
@akornich I don't think this solution is going to be work. There should be an automatic unhandled exception(crash log) tracking feature inside the Rollbar xamarin SDK. Developer needs to add only configuration(With Access Token) in the base code (Xamarin forms) for tracking/sending the crash log of each host. 

I would like to mention Rollbar React Native SDK here. In this SDK there is no need to write extra code for catching unhanlded exception (Crash log) and invoking Rollbar instance. Just Rollbar cofiguration(With Access Token) is required, it's automatically start tracking and sending the unhandled exception(Crash log) to the Rollbar console for each host platform(IOS/Android).

**Comment by RollbarExample** [comment]
> @RollbarExample , i just cloned the repo with your sample app. its Android project does not compile due to missing resources:
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	No resource found that matches the given name: attr 'windowActionBar'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2
> Error	No resource found that matches the given name: attr 'colorPrimaryDark'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2
> Error	Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2
> Error	No resource found that matches the given name: attr 'windowNoTitle'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2
> Error	No resource found that matches the given name: attr 'colorPrimary'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	2
> Error	No resource found that matches the given name: attr 'colorAccent'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	3
> Error	Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	4
> Error	No resource found that matches the given name: attr 'colorAccent'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	4
> Error	No resource found that matches the given name: attr 'windowActionModeOverlay'.	App5.Android	C:\Users\andrey\Downloads\Rollbar-Xamarin-Example-master\App5\App5.Android\Resources\values\styles.xml	4

I believe android api 8.1 is already installed in your android sdk. if not please install and rebuild again.

**Comment by akornich** [comment]
@RollbarExample , I think you missed subscription to this event in your OnCreate(...) method:
AndroidEnvironment.UnhandledExceptionRaiser += AndroidEnvironmentOnUnhandledException;

**Comment by RollbarExample** [comment]
So i have ran the attached app. See the correct traceback is not appearing.

![capture](https://user-images.githubusercontent.com/32199575/46492422-22ee6d80-c82b-11e8-888e-58e1ad1bdfdb.PNG)

**Comment by RollbarExample** [comment]
In case of caught exception it's working perfectly fine.

![capture](https://user-images.githubusercontent.com/32199575/46492557-88425e80-c82b-11e8-81be-801632c03769.PNG)

**Comment by akornich** [comment]
@RollbarExample , in case the uncaught exception the traceback could not be rendered because the UnhandledExceptionEventArgs  args object was passed to the RollbarInstance.Info(...) in the current app domain unhandled exceptions handler of App.xaml.cs instead of an Exception. Please, make sure your handler implementation looks like this: 
'        static void OnAppDomainUnhandledException(object sender, UnhandledExceptionEventArgs args)
        {
            System.Exception ex = (System.Exception)args.ExceptionObject;
            if (ex != null)
            {
                // RollbarLocator.RollbarInstance.Info("Exception is not null");
                Console.WriteLine(ex);
                try
                {
                    RollbarLocator.RollbarInstance
                        .AsBlockingLogger(TimeSpan.FromSeconds(5))
                        .Critical(ex)
                        ;
                }
                catch(System.Exception e)
                {
                    string test = e.Message;
                }
            }
        }
'

**Comment by akornich** [comment]
However, once you make this change you will notice that the exception will not be reported to the Rollbar API at all. The reason is that it appears that stack frame objects of an uncaught exception in Xamarin are way incomplete (and somewhat useless). This breaks current implementation of their interpretation within the Rollbar.NET notifier. I already filed this issue as #192 and I'll try to release a fix for it by the end of today.

**Comment by akornich** [comment]
#192

**Comment by RollbarExample** [comment]
@akornich Hey tested it with android. Exception is reporting but file name and line no is still missing. Here i have attached screenshot.

![capture](https://user-images.githubusercontent.com/32199575/46649795-0306d300-cbb8-11e8-91e8-8f942fedb9d8.PNG)

**Comment by akornich** [comment]
@RollbarExample , yes, that is expected - that is all info available from Xamarin environment when an exception is captured the current app domain unhandled exception event. if you do it via  AndroidEnvironment_UnhandledExceptionRaiser (as I described above) - you will get a bit better trace.
