### ISSUE TITLE
Add timeout in case the reporting process hangs

### ISSUE THREAD

**Issue by and-megan** [rollbar/Rollbar.NET#27]
In the events that calling the Rollbar service to log an event hangs, e.g. Rollbar or a proxy server is down, can there be a timeout?

**Comment by rokob** [comment]
This is something we should include in the new v1, c.f. https://github.com/rollbar/Rollbar.NET/milestone/1

**Comment by coryvirok** [comment]
@akornich is this done?

**Comment by akornich** [comment]
it should be fine in v1 now, since it has async nature of all the logging methods. in the latest code on the wsc fork, event construction of a payload happens on a worker thread. all the communications with Rollbar API service happens only on a worker thread where retries and timeout could take some significant time, but would not affect the client at all (it is completely internal business of Rollbar.NET's queue processing worker thread to deal with retries and timeouts).

**Comment by akornich** [comment]
In the wsc fork's codebase there is now a doc file (in the codebase root) that already describes conceptual design of v1 implementation.

**Comment by coryvirok** [comment]
Great. Closing this out.
