### ISSUE TITLE
Out of memory exception with high exceptions rate in multi threaded environment

### ISSUE THREAD

**Issue by sanjaysingh** [rollbar/Rollbar.NET#296]
**Describe the bug**
Rollbar seems to be causing out of memory issues when a multi threaded application causes burst of exceptions in short span of time.

**To Reproduce**
We were able to write a .Net console app with just the enough code to show the behavior that we think is affecting us. The memory usage keeps growing up when application is continuously pumping exceptions from multiple threads. In this example we only used 5 threads but in the real application where we use Rollbar we have 100s of threads. Understand that following example is just a representation of the issue to simplify reproducing of the problem; it does not depict how the Rollbar is being used in the application. In actual application, Rollbar is used with Log4Net using an appender.

The error can also be reproduced if you use incorrect access code that you might want to do so that Rollbar is not flooded with all these dummy exceptions.

```C#
using System;
using System.Threading.Tasks;
using System.Configuration;
using Rollbar;
using System.Diagnostics;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var config = new RollbarConfig(ConfigurationManager.AppSettings["Rollbar.AccessToken"])
            {
                Environment = "Development"
            };
            var rollBar = RollbarFactory.CreateNew().Configure(config);
            int threadsCount = 5;
            Console.WriteLine($"Enter to start sending stream of messages on {threadsCount} threads.");
            Console.ReadLine();
            for (int i = 0; i < threadsCount; i++)
            {
                Task.Run(() =>
                {
                    while (true)
                    {
                        rollBar.Error(new System.Exception("A dummy exception occurred".PadRight(1024, 'Z')));
                    }
                });

            }
            Task.Run(() => 
            {
                while (true)
                {
                    Console.WriteLine($"Memory used: {Process.GetCurrentProcess().PrivateMemorySize64 / (1024 * 1024) }MB");
                    Task.Delay(1000).Wait();
                }
            });
            Console.WriteLine("Done creating tasks. Enter to exit");
            Console.ReadLine();
        }
    }
}

```

**Expected behavior**
Flooding of exceptions should not cause extra memory pressure on the application just because we are trying to send those errors to Rollbar. Seems like the errors get cached in memory and it cannot keep with the rate of exceptions being generated. If the application is already under pressure because of some issues in downstream dependencies, the logger (Rollar) should not aggravate that situation. There might be a possibility of implementing some rate limiting / buffer limiting on the client side if it is not already there.

**Screenshots**
Memory graph taken from Visual Studio 2017 in-built memory profiler
![image](https://user-images.githubusercontent.com/1812362/52589662-66766b00-2e0d-11e9-9935-3279c82fbe7c.png)

Console log showing how memory usage is increasing
![image](https://user-images.githubusercontent.com/1812362/52589753-932a8280-2e0d-11e9-8bc6-38d71801083b.png)

**Rollbar Client - Rollbar.NET Hosting Environment**
 - Rollbar.NET Host type: Azure Worker Role, Console Application
 - OS and its version: Windows Server 2012, Windows 10
 - .NET flavor and its version: .Net Framework 4.6.2
 - Rollbar.NET Version: 2.1.0
 
 - Applicable custom third party logging library/framework integration (if any): Log4Net

**Comment by akornich** [comment]
@sanjaysingh , thanks for reporting the issue.
I'll look into the attached sample application a bit later today. But for now, I want to make sure there is a clear understanding of the basic concepts of Rollbar.NET inner structure.

**Comment by sanjaysingh** [comment]
@akornich  Thanks for prompt reply. In our case, we are using a single instance of the logger for the lifetime of the application. It also then uses a single access key that is configured when logger is created. Let us know if we are using the the Rollbar logger incorrectly causing this memory issue.

**Comment by akornich** [comment]
@sanjaysingh , what happens if you periodically invoke garbage collector while the test app running?

**Comment by sanjaysingh** [comment]
Haven't tried that. But i don't think it will make any difference. When running the memory profiler i see that the issue is with RollbarLogger class maintaining the dictionary of pending tasks. With flood of messages, these tasks just don't get scheduled fast enough and eventually cause out of memory.

![image](https://user-images.githubusercontent.com/1812362/52597874-2077d200-2e22-11e9-822a-b64aab015a57.png)

![image](https://user-images.githubusercontent.com/1812362/52597911-3e453700-2e22-11e9-9de8-16dee3f00cc3.png)

The queue depth of 20 does not really matter in this case because, the tasks itself are piling up to get scheduled to queue those messages. I think the depth smartness needs to be shifted little bit up the stack so that these unnecessary tasks don't get created in the first place.

**Comment by akornich** [comment]
@sanjaysingh , i just briefly looked at your test application code and it looks like you are starting 5 threads pumping exceptions into a single logger instance without any "sleep"/breath time left. How realistic is this scenario in the first place? 
I understand you are trying to simulate a busy server application. If your real application does something similar to this, you probably need to take close look into why it generates such a flood of exceptions (with virtually infinitely high rate). Also, when .NET runs on Windows server it runs its garbage collection in the server mode as opposed to running in the workstation mode (I am not saying it can fix the problem you are facing but it does make them as very different use cases). Another thing to keep in mind, in server environment  .NET has (at least it used to be some time ago) much larger thread pool than in non-server environment, and I think there is a way to increase even that number.
The point I am trying to make is that when you need to, for example, test your defense line, throwing a nuke on it and evaporating the whole thing does not provide you with any learning experience about how good or not it was as a defense line regardless of what purpose it was created for.

**Comment by sanjaysingh** [comment]
@akornich The sample code above as I had clearly mentioned was an attempt to replicate the issue that we faced in production and had to turn off Rollbar. So yes it is very much possible. Thread starvation can happen. It is not about increasing the thread count because no number of threads would be enough with the current structure that you have if the exceptions are flooded. We for sure working on fixing the issues that caused the flooding and will be implementing the Circuit breaker there. The important thing is we will fix what we find. What we don't know what we don't know and the things can repeat and we in no way want the the logger to be a bottleneck. Here is the lay of the land. It is unnecessary distraction in my opinion but just it case it is going to help you visualize better.

- An Azure Worker Role with multiple nodes has 10+ jobs running off .Net Tasks (not classic threads).

- All the jobs subscribes to Rabbit queues with PrefetchCount of 50.

- When there are too many messages in queues, there can be as many as 50 tasks per subscriptions so total of 500+ tasks in play. 

- We currently have Splunk and Azure AppInsight configured. We are additionally adding Rollbar for some important insight into exception it provides and also to add redundancy on the logging and monitoring. 

- Flooding of exceptions can happen for many reasons and we are improving on those as we learn. Splunk works off of Log4Net throgh file appender and Splunk forwarder out-of-process executable pumping the logs. AppInsight has something similar and so we never faced any issues with flooding of the logs causing the logger itself to choke. In fact, Spunk is how we triage this issue in the first place.

I am just trying to help myself and you figuring out a solution to this problem, but from the tone of your response I don't think you are interested in listening.

Let me know if you need any other data from me. I have given most of the details that matters here and am also clear on where the issue is in the code as i have shown above.

**Comment by akornich** [comment]
@sanjaysingh , I appreciate the effort you put into tracking down and reporting the issue. No doubt here.
That is exactly my point, starvation of the pool thread is a real issue that could happen in any application. That is why .NET provides a way to increase default thread count in the application thread pool as needed. Although you potentially may run into some other types of issues (like doing more thread context switching than actual useful work) while trying to increase the thread pool limit, the approach does work to some reasonable amount of threads in the pool.
Based on what you just reported, I believe the real cause of the issues you are facing is the thread starvation. According to your own estimates the application might use over 500 threads by design. If each of the threads generates even one exception around the same time, the Rollbar logger might need another 500+ threads to schedule payloads. Now in total we are already over 1K threads down in the pool. A couple of more async calls within the application threads during the same processing per thread and we are over 2K threads down in the pool.
Now, I just checked default value for worker threads limit in .NET console application on my machine - it is 2,047. Under .NET Core it is 32,767. Why? .NET Core is geared towards server/service applications in the first place. That explains much higher default limit.  
It looks like your application already places huge demand for threads from the pool, so adding into it a component that does rely on thread pool as well and proportionally to demands of the hosting applications - it does not help the situation.
What are possible solutions?
A few that come to mind:
1. try to allow more threads in the pool.
2. partition your application across multiple hardware hosts (with less message processing per host, hence less demand for pool threads)
3. make other third party libraries to watch their demand
4. TBD?
You are essentially suggesting to implement solution N3. Problem with this approach that a third party library has less application context about what is happening that the hosting application itself. Is it just a short spike in payload reports or a consistent pounding with payloads forever? What component/layer has better chance to know the reason.
Now, **we can stop scheduling payloads if we see that we are getting close or over the current thread pool max limit and start ignoring (throwing away) subsequent reports. That is a possibility.** But what if it was a short term spike in activity that could be eventually recoverable - while we actually lost the data by then. Also, what would be the condition to restart collection of payloads?
I just checked a payload scheduling performance on my ultra-portable laptop: it normally stays under 1 [msec] per payload (and we are talking about an exception with around 200 data rich stack frames to parse). A very small price to pay - assuming it was given a chance (i.e. a thread) to do so. That means 1000 payloads per second could be successfully scheduled if (again) were given a chance. Before any signs of "choking". While any finite time "choking" would be recoverable with time.
And now somewhat relevant point about the situation without going into any technical details. Rollbar.NET has built in maximum payload reporting limit per access token. It is 60 per minute. So, if you have 500 processing tasks generating even one exception per task not many of them will get delivered. And even if you increase the queue depth it could take long time to get them all to the Rollbar service. But event then if the 500 task present consistently keep adding new ones - a lot of payloads will be discarded. You may want to consider allocating something like a different access token per job.

**Comment by sanjaysingh** [comment]
@akornich if you notice the sample code, you will see that things break even with 5 Tasks. During triage process, we had reduced the PrefetchCount to 5 and Rollbar still seemed to hog memory. It has mainly to do with continuous pump of exceptions rather than number of threads. I am afraid we are not discussing the main issue but rather going around these unnecessary thread limitation issues in .Net.

Today even with these bursty loads and exceptions, things will eventually  be back to normal after few seconds of errors exhausting the retries. As soon as we bring Rollbar in, it causes out of memory just within few seconds of those bursty load and thus we don't have chance to recover. That is the crux of the issue we should be focusing on. If Rollbar was  not creating these infinite Tasks one per log message, i think these issues would not have happened. Don't you think, it is wasteful to create more Tasks that the queue depth specified? I am going to make that change and try to see how that works. If application is working fine without Rollbar, i don't have a justification to make any design change or anything at this time. Rollbar logger and related code can be changed as required.

One more thing that we have tried and it seems to work with linear memory growth rather than exponential is just adding 1 millisecond of delay after each Rollbar call and we are testing this currently.
``` C#
Task.Delay(1).Wait();
```

**Comment by sanjaysingh** [comment]
@akornich I made this change at https://github.com/sanjaysingh/Rollbar.NET/commit/17b3836a01225f8225178c7a730cb39b5e8422f8 to limit creating tasks and only have statically configurred consumers. It seems to work fine in local testing.

**Comment by akornich** [comment]
@sanjaysingh , v2.2.3 with the fix is out and is available on Nuget. Let me know is that unblocks you.

**Comment by sanjaysingh** [comment]
@akornich Thanks. We will give this a try and let you know if we see any issues. I am still interested in a fix to get rid of creating these Tasks for each message sent to Rollbar so would be interested in when do you plan to address that.

**Comment by akornich** [comment]
@sanjaysingh , i'll probably have the taskless implementation done by the end of upcoming week and published beginning of the following week.

**Comment by rokob** [comment]
The way we are doing this in other languages with similar primitives to C# is the following:

1. Some code calls an API method like `error` or `log`. This can be direct `Rollbar.log` or via an uncaught exception handler
2. The `log` method does a minimal amount of work to figure out if this is something that actually needs to be processed, if no then we short circuit and stop, if yes then
3. We push an object onto a queue [*]
4. On a separate thread [**] we read from the queue, do all the work that needs to be done to prepare the item to be sent to the API, and then send it to the API

*: This queue is fixed size and is the only communication point between threads so it is the only source of contention, but there usually isn't much contention because each thread operates on different ends of the queue

**: Typically one processing thread and one network thread, but that is abstracted from the surface API

Here we are creating Tasks as the mechanism of doing 3,4 above asynchronously without owning some dedicated threads. I'm not sure why we are storing references to the tasks in a map, we don't ever really use that map. Instead, we should just have one thread which reads from the front of a concurrent queue, and the calling thread can push onto the back of that queue. If the queue is full then either don't push, or drop the front to free space before pushing.

`Task` is generically a nice concurrency abstraction but it is the wrong one to use here. With the above setup, we can have a dedicated thread pool for processing or for the network if this cannot keep up with bursts, but creating more threads usually just creates more contention for an already scarce resource.

**Comment by akornich** [comment]
@rokob, thanks for summing it up!
One small correction. It should be:
"Here we are creating Tasks as the mechanism of doing 2,3 above asynchronously".

**Comment by sanjaysingh** [comment]
@rokob your summary in the 4 points above is to the point and yes it is the most common way of implementing producer/consumer i have seen as well. As for the storing the Task reference in the map, it does not really matter too much. I tried to play with completely getting rid of the in the code but that does not really go very far. Creating a Task for each message is just too much and runtime can't keep up with that.
I think the approach of just dumping the message into a fixed size queue and then having a separate one or more consumer to process them is the most stable solution.

Also to give an update, the 1 milliseconds delay fix that we had put in 2 days back did not go very far. It caused Out Of Memory today. We are upgrading to 2.2.3 today and should be having some data in a couple of days next week. This time I saw the Out Of Memory with not as much load (2000 exceptions in 24 hours) and I am not sure why as it does not align with the busty load theory. It is possible that there is some other crazy threading use case / issue that we don't know yet. We will see. Either way i think cleaning up this per message Task creation should help things stabilize.

**Comment by sanjaysingh** [comment]
> @sanjaysingh , i'll probably have the taskless implementation done by the end of upcoming week and published beginning of the following week.

That is awesome! Thank you @akornich

**Comment by akornich** [comment]
@sanjaysingh , when you say:
"This time I saw the Out Of Memory with not as much load (2000 exceptions in 24 hours)"
do you mean 2000 exception logging calls to RollbarLogger in 24 hours, or that is amount that eventually made it through to the Rollbar Dashboard?
BTW, regarding the "1 milliseconds delay": our measurements show under 0.01[msec] async task call vs 0.8-1.1[msec] sync call difference using identical payload objects. That is close to 2 orders of magnitude. Definitely it is worth trying. The only problem we should've stayed away from using Tasks. The upcoming task-less implementation should be able to achieve similar performance but without relying on the Tasks "black box" that apparently misbehaves under extreme loads.

**Comment by akornich** [comment]
@sanjaysingh , oops, i think i misunderstood initially what you meant by "1 milliseconds delay". However, the info i provided for that is still relevant for the issue :)

**Comment by sanjaysingh** [comment]
> @sanjaysingh , when you say:
> "This time I saw the Out Of Memory with not as much load (2000 exceptions in 24 hours)"
> do you mean 2000 exception logging calls to RollbarLogger in 24 hours, or that is amount that eventually made it through to the Rollbar Dashboard?

I meant 2000 exceptions thrown by the application and hence tried to be logged into Rollbar. I did not check how many actually made to the Rollbar.

**Comment by akornich** [comment]
@sanjaysingh , i see. Thanks for the clarification.
Without going into too much details of my latest experiments, the more i play with this scenario the more i get convinced that what actually fundamentally happening is: if there are "too many" long-lasting busy threads running at the "same time" the dynamically allocated short term tasks get never executed once such high activity of the busy threads starts happening. Event regardless of how many or few the short term task you are trying to allocate. The few or many - just never execute.
BTW, are you, guys, using any other libraries (in addition to Rollbar SDK) or in your own application code Task instances in what could be called "in significant numbers". If yes, did you ever notice anything odd that they may be also failing to execute at some point?

**Comment by sanjaysingh** [comment]
We have log4net with file appender, AppInsight SDK. We also use EasyNetQ for talking to RabbitMQ. We haven't see a thread starvation issue before. With EasyNetQ, the prefetch count determines how many Tasks it can create. Currently it is set to 5 but even with 50 we did not face any such issues. This application has been in production for 3 years now so it is pretty battle tested to handle these loads.

**Comment by akornich** [comment]
@sanjaysingh , and what about estimated count of "long-running" ("at the same time") and "busy" threads or tasks?

**Comment by snakefoot** [comment]
The global Tasks-ThreadPool is a limited resource one should be careful when using it. Swarming the global ThreadPool with non-critical tasks will hurt performance. Logging should not drain the resources of a system.

Like also mentioned here https://github.com/rollbar/Rollbar.NET/pull/225#issue-235217886 then it gives a  "huge" overhead to allocate (and schedule) a Task to just enqueue a LogEvent.

**Comment by sanjaysingh** [comment]
> @sanjaysingh , and what about estimated count of "long-running" ("at the same time") and "busy" threads or tasks?

We don't have any explicit long running Tasks that we create. We, however have 10 timer based jobs which run every 5-10 minutes and then we have Rabbit subscriptions as I mentioned in detail above. I don't for sure how EasyNetQ manages these but it appears that i has 1 Task per queue so 10 for these subscriptions.

**Comment by akornich** [comment]
@sanjaysingh , thanks!
a quick update on the upcoming changes status: 
- the basic hierarchy of the packaging strategies is done and available in my fork:
[https://github.com/WideSpectrumComputing/Rollbar.NET](https://github.com/WideSpectrumComputing/Rollbar.NET)
- fine tuning the hierarchy today
- starting (today/tomorrow) working on removal of the Tasks.

**Comment by sanjaysingh** [comment]
@akornich @rokob Just to update on 2.2.3. We are still getting Out of Memory issues with this update. It meas there is some other bug in the SDK that we don't know yet about. It is difficult to run profiler as it all happens very quickly so I will still have to see how to reproduce this.

**Comment by akornich** [comment]
@sanjaysingh , here are my notes for another experiment with your sample/test app that i performed the other day:
i completely eliminated that collection that used to be registering the packaging tasks. Ran it with 5 threads feeding exceptions bumper-to-bumper. Everything  works as expected: no memory usage increase, the exceptions keep coming to Rollbar API every second. During this time the transmission queue is always full (20 items). Then, i increase the feeding threads to 50. Nothing gets to Rollbar API at all. I start debugging and find out that the transmission queue is completely empty all the time. That could only happen if the scheduled packaging tasks get never executed. i place a breakpoint into the packaging method the execution never gets there. And, in this case the memory starts growing crazy fast and the app runs out of it in matter of couple of minutes (yes, the scheduled tasks are never executed and stay queued up for it to happen).  So, it is a clear sign that past some threshold of feeding threads no scheduled task ever gets invoked. On my machine that threshold happens somewhere over 40 feeding threads. 

Do you think there is some reasonable correlation of this test with what you are observing now?

Let's see how the "Task-less" version of the SDK performs in the same condition...

**Comment by rokob** [comment]
I don't see a point in doing any testing with Tasks, that approach is just swamping the shared thread pool and we know it isn't tenable going forward.

**Comment by akornich** [comment]
yes, i am on track to have usable Task-less version by the end of this week.

**Comment by sanjaysingh** [comment]
@akornich I think you might have seen the memory issue with increasing thread before 2.2.3. In the sample app, i cannot reproduce the issue using 2.2.3 even with 50 Tasks. It did went to 100MB from 30MB in 5+ minutes but it stayed there. There seems to be some other use case we are not able to figure out. We will take the Task-less version when it is available and give that a try.

**Comment by akornich** [comment]
@sanjaysingh , the Task-less SDK version is out:
[https://github.com/rollbar/Rollbar.NET/releases/tag/v3.0.0-preview](https://github.com/rollbar/Rollbar.NET/releases/tag/v3.0.0-preview)
[https://www.nuget.org/packages/Rollbar/3.0.0-preview](https://www.nuget.org/packages/Rollbar/3.0.0-preview) 
Since you mentioned you are using it via Log4net, please, make sure you are using the latest Rollbar logger (i did not publish upgraded log4net plug-in yet).
Good luck giving it a test run! My tests showed much better results than the v2.

**Comment by sanjaysingh** [comment]
@akornich There are some extra dependencies that seem to be introduced here? Is it intentional? Why does it need AspNet MVC and all its Razor components. It does not make sense for our Worker Roles to have these unnecessary dependencies. Can you please verify?

![image](https://user-images.githubusercontent.com/1812362/53429681-1b3a8b80-39bb-11e9-8d9e-57119ec3736c.png)

**Comment by akornich** [comment]
@sanjaysingh, we have users that host Rollbar Notifier within .NET Framework, .NET Core, .NET Standard, Mono, Xamarin based application. Some of the applications are web services, web apps, desktop or console apps, mobile, etc. All of them are asking for easier integration of Rollbar within their specific implementation of .NET Standard and their specific app development framework (like Windows Forms vs WPF, WebForms vs ASP.NET MVC, etc.). For our plan is to keep dependencies of these integrations minimized by conditional compilation when we go across different .NET platform implementations, but to "bundle" up all the different dependencies of the same .NET platform implementation. We do break out support of common third party logging libraries via dedicated plug-ins that are implemented as separate distributables. 
All the dependencies are handled via Nuget packages so there is no extra inconvenience for the developers to get them except the fact that they do get some "unnecessary" ones depending on their specific hosting scenario for Rollbar Notifier.

That is our current approach to keeping somewhat optimal balance between wide range of integrations and having smaller amount of Rollbar SDK deployment units/packages.
However, if there is high demand for keeping the things very granular, we can definitely take a route  of having very generic Rollbar Core package and moving each and every integration with specific framework, framework area/app-type or a third party library in separate dedicated packages.

Now back to your immidiate question: 
is it a show stopper for you to have these Mvc and WebApi.Core dependencies? Or this is just a preference that you would like us to address eventually by having more granular integration packages?

**Comment by sanjaysingh** [comment]
@akornich For now we are explicitly removing those MVC dependencies after installing the package because it unnecessarily creates binding redirects because of version mismatch between what we have already and what is referred here. It is also adding unwanted assemblies worker roles. I was mainly asking from the perspective of what changed between 2.2.3 and 3.0 that resulted into these extra dependencies.

**Comment by akornich** [comment]
@sanjaysingh, I see. Yes, these new dependencies were part of the feature request that also triggered the idea of adding the payload packagers and their decorators in v3.0 that also happened to work well with the removal of the Tasks from Rollbar SDK API.
We are currently having an internal discussion regarding splitting out the integrations from the core functionality. So, that could be coming soon...

**Comment by sanjaysingh** [comment]
@akornich We tried to see if Rollbar upgrade goes well without taking MVC dependencies but it seems to cause all sorts of issues. We are not able to update because of this new MVC dependencies. Rollbar issues 4.0 and we already have 5.2.3; it is causing all sorts of compatibility issues. It automatically adds binding redirects but that does not seem to work either. Is there any way this extra MVC dependency can be moved out quickly? It is an unnecessary distraction from what we wanted to test currently.

**Comment by akornich** [comment]
@sanjaysingh , I am in the process of testing splitting out MVC related functionality. I should be able to make another preview release by the end of today.

**Comment by akornich** [comment]
@sanjaysingh , v3.0.1-preview (with dependencies cleaned-up) is available on Nuget (it may take a few more minutes for Nuget to finish updating indexes).

**Comment by sanjaysingh** [comment]
@akornich Thank you for prompt reply. I am going to try that now.
