### ISSUE TITLE
[DOUBT] On Xamarin Forms, it's reported when the app crashs offline?

### ISSUE THREAD

**Issue by aismaniotto** [rollbar/Rollbar.NET#413]
Hi,

I would know if the Rollbar offers support to reports when that happens offline. When gets a connection, I will receive the report?

Thanks.

**Comment by akornich** [comment]
Hi @aismaniotto , regardless of what platform Rollbar.NET SDK runs on, it currently does not implement payload persistence. However, it does have internal in-memory queues storing the payloads until successful transmission or until exceeding specified number of retries (currently it is 3). So that it can deal with intermittent disconnections (not very long ones). Currently, the depth of the queues could be configured as needed (while default is 20). We can easily add support for reconfigurability of the max number of retries if needed.
In case your use cases do require true persistence of the payloads in case of poor connectivity with relatively long disconnection times, please, file here a feature request providing as much as possible details about your expectations regarding what are the timeout conditions for giving up on the payloads if the disconnection time is "too long", or any limit of retries to send the persisted payloads before giving up on them, etc.
So far we did not have any request yet for the payload persistence feature, but we would gladly consider adding one if there is a demand for it.

**Comment by aismaniotto** [comment]
Thank you very much for the reply. I go raise the requirements and after that, open a feature request.
