### ISSUE TITLE
Auto-Capture documentation

### ISSUE THREAD

**Issue by Lobosque** [rollbar/Rollbar.NET#425]
Thanks for the new auto-capture features added in the latest release!
Where can I find documentation on setting it up?
Also, the request capture was implemented for dot net core? If not, is it going to be implemented?

**Comment by akornich** [comment]
Hi @Lobosque , I assume your questions are mainly related to our plug-in for Asp.Net Core: [https://www.nuget.org/packages/Rollbar.NetCore.AspNet/](https://www.nuget.org/packages/Rollbar.NetCore.AspNet/).
In case you already have the plug-in integrated into your application and working, you do not need to do anything on your side to add auto-capture of requests and responses along with relevant payloads. That is why it is auto- :) 
The requests capture existed since the day of the first release of the plug-in. The responses capture was just added with the last release.
So, you should be fine getting both captured with no extra work on your part.
Let me know if I missed something here or you are not getting it working on your side as promised, for some reason.
Best regards,
- Andrey

**Comment by akornich** [comment]
Hi @Lobosque, can we close this issue or you still need some help?

**Comment by Lobosque** [comment]
@akornich thanks for clarifying, we're all set.

**Comment by akornich** [comment]
Hi @Lobosque, can you, please, provide some details on how you actually integrate Rollbar.NET into your application? Also, what is/are your application target framework/s (.NET, .NET Core, Xamarin, etc.) and its version? Are you using our core Rollbar Nuget package or any of our plug-ins or extensions (these usually have longer Rollbar.xyz... like names)? 
Or, batter yet, if you could post a simple repro app mimicking how your real app integrates this SDK  while demonstrating the problem you are facing...

**Comment by akornich** [comment]
closing due to no replies...
