### ISSUE TITLE
Report Proper Client IP When Behind Load Balancer

### ISSUE THREAD

**Issue by StrangeWill** [rollbar/Rollbar.NET#74]
As far as I can tell: X-Forwarded-For is not checked by default nor is there a way to enable checking it.

So I always report the load balancer IP address as the source.

**Comment by akornich** [comment]
@StrangeWill , can you, please, clarify what your use case is and what you would like to get added to the SDK? it looks like XFF header was designed in so that a proxy server could add distinct client IP while routing requests to the outside world. i am not sure that rollbar.net should be adding the header. of cause, i am not an expert in http header fields, just did some reading on the field and that is my understanding of its purpose...

**Comment by StrangeWill** [comment]
I think this may be a non-issue, may have gotten this lib mixed up with RollbarSharp. Sorry about that. In Rollbar.NET I can override the User IP payload myself.

**Comment by akornich** [comment]
No problem at all. BTW, would it be useful if we add an ability to the Rollbar.NET notifier to internally detect the host ip address and assign it as default value for UserIP at the time of payload object construction?
